[global]
    workgroup = HOME
    server string = Samba Server
    netbios name = NOTEBOOK
######## Setup charsets
    dos charset = cp1251
    unix charset = utf8
######## Setup logging
    log file = /var/log/samba/%m.log
    max log size = 50
    max xmit = 65536
    debug level = 1
######## Setup daemon settings
    domain master = No
    preferred master = Yes
#    socket options = IPTOS_LOWDELAY TCP_NODELAY SO_SNDBUF=65536 SO_RCVBUF=65536 SO_KEEPALIVE
    os level = 65
    use sendfile = Yes
    dns proxy = No
    dont descend = /proc,/dev,/etc
    deadtime = 15
######## Enable synlinks
    unix extensions = No
    wide links = yes
    follow symlinks = yes
######## Securtity settings
    security = user
    map to guest = Bad User
    guest account = nobody
    guest ok = yes
#    auth methods = guest, sam_ignoredomain
    create mask = 0664
    directory mask = 2755
    force create mode = 0644
    force directory mode = 2755
    hide dot files = yes

######## Пользовательские ресурсы
    usershare path = /var/lib/samba/usershares
    usershare max shares = 10
    usershare allow guests = yes
    usershare owner only = yes

[PublicShare]
    comment = Общий ресурс, в котором archie имеет доступ на запись
    path = ${HOME}/Общедоступные
    public = yes
    read only = yes
    write list = archie
    printable = no

[guests]
  comment = Ресурс, разрешающий чтение и запись всем пользователям
  path = ${HOME}/Общедоступные
  public = yes
  only guest = yes
  writable = yes
  printable = no
