[global]
  workgroup = HOME
  server string = Samba Server
  netbios name = NOTEBOOK

## Логирование
  log file = /var/log/samba/%m.log
  logging = syslog

## Включение следования по символическим ссылкам
  follow symlinks = yes
  wide links = yes
  unix extensions = no

## Ограничение версии протокола
  server min protocol = SMB2_02
  ; server max protocol = SMB3

## Увеличение пропускной способности
  server multi channel support = yes
  deadtime = 30
  use sendfile = yes
  min receivefile size = 16384
  aio read size = 1
  aio write size = 1
  ;socket options = IPTOS_LOWDELAY TCP_NODELAY IPTOS_THROUGHPUT SO_RCVBUF=131072 SO_SNDBUF=131072

## Установка и форсирование прав доступа
  ;inherit owner = unix only ; Наследовать владельца родительского каталога для новых файлов и каталогов
  ;inherit permissions = yes ; Наследовать разрешения родительского каталога для новых файлов и каталогов
  create mask = 0664
  directory mask = 2755
  force create mode = 0644
  force directory mode = 2755

## Создание ресурсов общего доступа от имени обычного пользователя
  usershare path = /var/lib/samba/usershares
  usershare max shares = 10
  usershare allow guests = yes
  usershare owner only = yes

## гостевой аккаунт
  guest ok = yes
  map to guest = Bad User
  map to guest = Bad Password

## Создание общего ресурса для анонимных пользователей
  security = user
  map to guest = bad user
  guest account = guest

## Создание общего ресурса для анонимных пользователей
[Общедоступные]
    comment = Ресурс, разрешающий чтение и запись всем пользователям
    path = /home/notebook/Общедоступные/
    public = yes
    only guest = yes
    writable = yes
    printable = no
