#! /bin/sh

set -E
exec > ~/.bspwm_error.log 2>&1

bspc rule -r "*"
pgrep -x sxhkd > /dev/null || sxhkd &
 
###---Autostart---###
# Language
setxkbmap "us,ru,ua" ",winkeys" "grp:alt_shift_toggle,grp_led:scroll" &
# feh
$HOME/.fehbg &
# Dunts
# /usr/bin/dunst &
# Polybar
$HOME/.config/polybar/launch.sh &
# Picom (Compton)
picom -b --experimental-backends --config $HOME/.config/picom/picom.conf &
# picom --experimental-backends -b --backend glx --vsync --xrender-sync-fence --glx-no-rebind-pixmap --use-damage --glx-no-stencil --config $HOME/.config/picom/picom.conf &
# Numlockx ON
numlockx on &
# Touchpad OFF
xinput disable 18 &
# Automount USB
udiskie &
# Cursor
xsetroot -cursor_name left_ptr &
 
###---MONITORS---###
# bspc monitor -d I II III IV V VI VII VIII IX X
bspc monitor -d I II III IV V
 
###---Monitor And Desktop Settings----###
bspc config border_width                  3
bspc config window_gap                    4
bspc config top_padding                   16
bspc config bottom_padding                0
bspc config left_padding                  0
bspc config right_padding                 0
# bspc config click_to_focus                true
bspc config split_ratio                   0.50
# bspc config focus_by_distance             true
# bspc config focus_follows_pointer         true
bspc config focus_follows_pointer         false
# bspc config history_aware_focus           true
bspc config remove_disabled_monitors      true
bspc config merge_overlapping_monitors    true
bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner

#РЕЖИМ МОНОКЛЯ КОГДА ОТКРЫТО ОДНО ОКНО
bspc config single_monocle	     false
# bspc config single_monocle	    true 

#ОТКЛЮЧЕНИЕ ГАПСОВ РАМОК И ОТСТУПОВ КОГДА ОТКРЫТО ОДНО ОКНО
bspc config borderless_monocle   false
bspc config gapless_monocle      false
# bspc config paddingless_monocle	 true

bspc config normal_border_color	"#4c566a"
bspc config active_border_color	"#1e1e1e"
bspc config focused_border_color "#327bd1"
bspc config presel_feedback_color "#327bd1"
# bspc config urgent_border_color "#dd2727"
 
###---Rules---###
# Проверьте имя класса программы
# xprop | grep WM_CLASS
bspc rule -a Google-chrome desktop='^2' follow=on
bspc rule -a Gimp desktop='^3' follow=on
bspc rule -a Inkscape desktop='^4' follow=on
bspc rule -a Deadbeef desktop='^5' follow=off
bspc rule -a kcalc state=floating
bspc rule -a Pavucontrol state=floating rectangle=670x350+685+24
# bspc rule -a dolphin state=floating
bspc rule -a dolphin desktop='^5' follow=on
bspc rule -a xfreerdp rectangle=1350x744

# bspc rule -a firefox state=floating follow=off rectangle=1350x900+50+90 desktop='^1'
# bspc rule -a TelegramDesktop state=floating follow=off desktop='^1'
# #bspc rule -a TelegramDesktop state=floating follow=off rectangle=420x900+1450+90 desktop='^1'
# bspc rule -a Steam state=floating follow=off rectangle=1350x900+285+90 desktop='^6' 
# bspc rule -a mpv state=floating rectangle=800x450+560+315 follow=off
# bspc rule -a dmenu rectangle=900x22+610+90
# bspc rule -a Media viewer rectangle=1350x900+285+90 state=floating
# bspc rule -a Inkscape desktop='^3'
# bspc rule -a Blender desktop='^2'
