#! /bin/sh
bspc rule -r "*"
pgrep -x sxhkd > /dev/null || sxhkd &
 
###---Autostart---###
# Language
setxkbmap "us,ru,ua" ",winkeys" "grp:alt_shift_toggle,grp_led:scroll" &
# feh
$HOME/.fehbg &
# Dunts
/usr/bin/dunst &
# Polybar
$HOME/.config/polybar/launch.sh &
# Picom (Compton)
# picom -b --experimental-backends &
picom --experimental-backends -b --backend glx --vsync --xrender-sync-fence --glx-no-rebind-pixmap --use-damage --glx-no-stencil --config $HOME/.config/picom/picom.conf &
# Numlockx ON
numlockx on &
# Touchpad OFF
xinput disable 18 &
# Automount USB
udiskie &
# Cursor
xsetroot -cursor_name left_ptr &
 
###---MONITORS---###
# bspc monitor -d I II III IV V VI VII VIII IX X
bspc monitor -d I II III IV V
 
###---Monitor And Desktop Settings----###
bspc config border_width                  2
bspc config window_gap                    8
bspc config top_padding                   16
bspc config bottom_padding                0
bspc config left_padding                  0
bspc config right_padding                 0
bspc config single_monocle                false
bspc config click_to_focus                true
bspc config split_ratio                   0.50
bspc config borderless_monocle            true
bspc config gapless_monocle               true
bspc config focus_by_distance             true
# bspc config focus_follows_pointer         true
bspc config focus_follows_pointer         false
bspc config history_aware_focus           true
bspc config remove_disabled_monitors      true
bspc config merge_overlapping_monitors    true
bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner

bspc config normal_border_color	"#4c566a"
bspc config active_border_color	"#1e1e1e"
bspc config focused_border_color "#327bd1"
bspc config presel_feedback_color "#327bd1"
bspc config urgent_border_color "#dd2727"
 
###---Rules---###
bspc rule -a "Gimp-2.10" desktop='^5' state=floating follow=on
bspc rule -a "Google-chrome" desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
